# GitHub Action for generating a contribution graph with a snake eating your contributions.
name: Generate Snake

on:
  schedule:
    # run automatically every 2 hours
    - cron: "0 9/4 * * *"

  # This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

  # run on every push on the master branch
  push:
    branches:
    - main
    
# The sequence of runs in this workflow:
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:    
      # Generates the snake  
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs:
            dist/github-snake.svg
            # dist/github-snake-dark.svg?palette=github-dark
            # dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
          

      # Or push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

